//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.UchetMedosmotrov4
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Инд напр медосм.
    /// </summary>
    // *** Start programmer edit section *** (ИндНапрМедосм CustomAttributes)

    // *** End programmer edit section *** (ИндНапрМедосм CustomAttributes)
    [AutoAltered()]
    [Caption("Инд напр медосм")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ИндНапрМедосмE", new string[] {
            "НомерДок as \'Номер документа\'",
            "Дата as \'Дата\'",
            "Организация as \'Организация\'",
            "Организация.Наименование as \'Наименование\'",
            "МедУчреждение as \'Медицинское учреждение\'",
            "МедУчреждение.Наименование as \'Наименование\'",
            "Сотрудники as \'Сотрудники\'",
            "Сотрудники.IDСотрудника as \'ID сотрудника\'",
            "Сотрудники.ФИО as \'ФИО\'",
            "Сотрудники.ДатаРождения as \'Дата рождения\'",
            "Сотрудники.Должности.Наименование as \'Должность\'",
            "Сотрудники.Должности.Подразделения.Наименование as \'Подразделение\'"})]
    [AssociatedDetailViewAttribute("ИндНапрМедосмE", "ВреднФактПроиз", "ВреднФактПроизE", true, "", "Вредные факторы производства", true, new string[] {
            ""})]
    [MasterViewDefineAttribute("ИндНапрМедосмE", "Организация", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Наименование")]
    [MasterViewDefineAttribute("ИндНапрМедосмE", "МедУчреждение", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Наименование")]
    [MasterViewDefineAttribute("ИндНапрМедосмE", "Сотрудники", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ФИО")]
    [View("ИндНапрМедосмL", new string[] {
            "НомерДок as \'Номер документа\'",
            "Дата as \'Дата\'",
            "Сотрудники.ФИО as \'ФИО\'",
            "МедУчреждение.Наименование as \'Медицинское учреждение\'"})]
    public class ИндНапрМедосм : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДата = System.DateTime.Now;
        
        private int fНомерДок;
        
        private IIS.UchetMedosmotrov4.Организация fОрганизация;
        
        private IIS.UchetMedosmotrov4.Сотрудники fСотрудники;
        
        private IIS.UchetMedosmotrov4.МедУчреждение fМедУчреждение;
        
        private IIS.UchetMedosmotrov4.DetailArrayOfВреднФактПроиз fВреднФактПроиз;
        
        // *** Start programmer edit section *** (ИндНапрМедосм CustomMembers)

        // *** End programmer edit section *** (ИндНапрМедосм CustomMembers)

        
        /// <summary>
        /// Дата.
        /// </summary>
        // *** Start programmer edit section *** (ИндНапрМедосм.Дата CustomAttributes)

        // *** End programmer edit section *** (ИндНапрМедосм.Дата CustomAttributes)
        public virtual System.DateTime Дата
        {
            get
            {
                // *** Start programmer edit section *** (ИндНапрМедосм.Дата Get start)

                // *** End programmer edit section *** (ИндНапрМедосм.Дата Get start)
                System.DateTime result = this.fДата;
                // *** Start programmer edit section *** (ИндНапрМедосм.Дата Get end)

                // *** End programmer edit section *** (ИндНапрМедосм.Дата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ИндНапрМедосм.Дата Set start)

                // *** End programmer edit section *** (ИндНапрМедосм.Дата Set start)
                this.fДата = value;
                // *** Start programmer edit section *** (ИндНапрМедосм.Дата Set end)

                // *** End programmer edit section *** (ИндНапрМедосм.Дата Set end)
            }
        }
        
        /// <summary>
        /// НомерДок.
        /// </summary>
        // *** Start programmer edit section *** (ИндНапрМедосм.НомерДок CustomAttributes)

        // *** End programmer edit section *** (ИндНапрМедосм.НомерДок CustomAttributes)
        public virtual int НомерДок
        {
            get
            {
                // *** Start programmer edit section *** (ИндНапрМедосм.НомерДок Get start)

                // *** End programmer edit section *** (ИндНапрМедосм.НомерДок Get start)
                int result = this.fНомерДок;
                // *** Start programmer edit section *** (ИндНапрМедосм.НомерДок Get end)

                // *** End programmer edit section *** (ИндНапрМедосм.НомерДок Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ИндНапрМедосм.НомерДок Set start)

                // *** End programmer edit section *** (ИндНапрМедосм.НомерДок Set start)
                this.fНомерДок = value;
                // *** Start programmer edit section *** (ИндНапрМедосм.НомерДок Set end)

                // *** End programmer edit section *** (ИндНапрМедосм.НомерДок Set end)
            }
        }
        
        /// <summary>
        /// Инд напр медосм.
        /// </summary>
        // *** Start programmer edit section *** (ИндНапрМедосм.МедУчреждение CustomAttributes)

        // *** End programmer edit section *** (ИндНапрМедосм.МедУчреждение CustomAttributes)
        [PropertyStorage(new string[] {
                "МедУчреждение"})]
        [NotNull()]
        public virtual IIS.UchetMedosmotrov4.МедУчреждение МедУчреждение
        {
            get
            {
                // *** Start programmer edit section *** (ИндНапрМедосм.МедУчреждение Get start)

                // *** End programmer edit section *** (ИндНапрМедосм.МедУчреждение Get start)
                IIS.UchetMedosmotrov4.МедУчреждение result = this.fМедУчреждение;
                // *** Start programmer edit section *** (ИндНапрМедосм.МедУчреждение Get end)

                // *** End programmer edit section *** (ИндНапрМедосм.МедУчреждение Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ИндНапрМедосм.МедУчреждение Set start)

                // *** End programmer edit section *** (ИндНапрМедосм.МедУчреждение Set start)
                this.fМедУчреждение = value;
                // *** Start programmer edit section *** (ИндНапрМедосм.МедУчреждение Set end)

                // *** End programmer edit section *** (ИндНапрМедосм.МедУчреждение Set end)
            }
        }
        
        /// <summary>
        /// Инд напр медосм.
        /// </summary>
        // *** Start programmer edit section *** (ИндНапрМедосм.Организация CustomAttributes)

        // *** End programmer edit section *** (ИндНапрМедосм.Организация CustomAttributes)
        [PropertyStorage(new string[] {
                "Организация"})]
        [NotNull()]
        public virtual IIS.UchetMedosmotrov4.Организация Организация
        {
            get
            {
                // *** Start programmer edit section *** (ИндНапрМедосм.Организация Get start)

                // *** End programmer edit section *** (ИндНапрМедосм.Организация Get start)
                IIS.UchetMedosmotrov4.Организация result = this.fОрганизация;
                // *** Start programmer edit section *** (ИндНапрМедосм.Организация Get end)

                // *** End programmer edit section *** (ИндНапрМедосм.Организация Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ИндНапрМедосм.Организация Set start)

                // *** End programmer edit section *** (ИндНапрМедосм.Организация Set start)
                this.fОрганизация = value;
                // *** Start programmer edit section *** (ИндНапрМедосм.Организация Set end)

                // *** End programmer edit section *** (ИндНапрМедосм.Организация Set end)
            }
        }
        
        /// <summary>
        /// Инд напр медосм.
        /// </summary>
        // *** Start programmer edit section *** (ИндНапрМедосм.Сотрудники CustomAttributes)

        // *** End programmer edit section *** (ИндНапрМедосм.Сотрудники CustomAttributes)
        [PropertyStorage(new string[] {
                "Сотрудники"})]
        [NotNull()]
        public virtual IIS.UchetMedosmotrov4.Сотрудники Сотрудники
        {
            get
            {
                // *** Start programmer edit section *** (ИндНапрМедосм.Сотрудники Get start)

                // *** End programmer edit section *** (ИндНапрМедосм.Сотрудники Get start)
                IIS.UchetMedosmotrov4.Сотрудники result = this.fСотрудники;
                // *** Start programmer edit section *** (ИндНапрМедосм.Сотрудники Get end)

                // *** End programmer edit section *** (ИндНапрМедосм.Сотрудники Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ИндНапрМедосм.Сотрудники Set start)

                // *** End programmer edit section *** (ИндНапрМедосм.Сотрудники Set start)
                this.fСотрудники = value;
                // *** Start programmer edit section *** (ИндНапрМедосм.Сотрудники Set end)

                // *** End programmer edit section *** (ИндНапрМедосм.Сотрудники Set end)
            }
        }
        
        /// <summary>
        /// Инд напр медосм.
        /// </summary>
        // *** Start programmer edit section *** (ИндНапрМедосм.ВреднФактПроиз CustomAttributes)

        // *** End programmer edit section *** (ИндНапрМедосм.ВреднФактПроиз CustomAttributes)
        public virtual IIS.UchetMedosmotrov4.DetailArrayOfВреднФактПроиз ВреднФактПроиз
        {
            get
            {
                // *** Start programmer edit section *** (ИндНапрМедосм.ВреднФактПроиз Get start)

                // *** End programmer edit section *** (ИндНапрМедосм.ВреднФактПроиз Get start)
                if ((this.fВреднФактПроиз == null))
                {
                    this.fВреднФактПроиз = new IIS.UchetMedosmotrov4.DetailArrayOfВреднФактПроиз(this);
                }
                IIS.UchetMedosmotrov4.DetailArrayOfВреднФактПроиз result = this.fВреднФактПроиз;
                // *** Start programmer edit section *** (ИндНапрМедосм.ВреднФактПроиз Get end)

                // *** End programmer edit section *** (ИндНапрМедосм.ВреднФактПроиз Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ИндНапрМедосм.ВреднФактПроиз Set start)

                // *** End programmer edit section *** (ИндНапрМедосм.ВреднФактПроиз Set start)
                this.fВреднФактПроиз = value;
                // *** Start programmer edit section *** (ИндНапрМедосм.ВреднФактПроиз Set end)

                // *** End programmer edit section *** (ИндНапрМедосм.ВреднФактПроиз Set end)
            }
        }
        
        // *** Start programmer edit section *** (ИндНапрМедосм.Печать CustomAttributes)

        // *** End programmer edit section *** (ИндНапрМедосм.Печать CustomAttributes)
        [ICSSoft.STORMNET.AccessType(ICSSoft.STORMNET.AccessType.none)]
        public virtual void Печать()
        {
            // *** Start programmer edit section *** (ИндНапрМедосм.Печать method implementation)

            return;
            // *** End programmer edit section *** (ИндНапрМедосм.Печать method implementation)
        }
        
        // *** Start programmer edit section *** (ИндНапрМедосм.Удалить CustomAttributes)

        // *** End programmer edit section *** (ИндНапрМедосм.Удалить CustomAttributes)
        [ICSSoft.STORMNET.AccessType(ICSSoft.STORMNET.AccessType.none)]
        public virtual void Удалить()
        {
            // *** Start programmer edit section *** (ИндНапрМедосм.Удалить method implementation)

            return;
            // *** End programmer edit section *** (ИндНапрМедосм.Удалить method implementation)
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ИндНапрМедосмE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ИндНапрМедосмE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ИндНапрМедосмE", typeof(IIS.UchetMedosmotrov4.ИндНапрМедосм));
                }
            }
            
            /// <summary>
            /// "ИндНапрМедосмL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ИндНапрМедосмL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ИндНапрМедосмL", typeof(IIS.UchetMedosmotrov4.ИндНапрМедосм));
                }
            }
        }
    }
}
