//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.UchetMedosmotrov4
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Класс вред факт.
    /// </summary>
    // *** Start programmer edit section *** (КлассВредФакт CustomAttributes)

    // *** End programmer edit section *** (КлассВредФакт CustomAttributes)
    [AutoAltered()]
    [Caption("Класс вред факт")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("КлассВредФактE", new string[] {
            "Наименование as \'Наименование\'"})]
    [View("КлассВредФактL", new string[] {
            "Наименование as \'Наименование\'"})]
    public class КлассВредФакт : ICSSoft.STORMNET.DataObject
    {
        
        private string fНаименование;
        
        // *** Start programmer edit section *** (КлассВредФакт CustomMembers)

        // *** End programmer edit section *** (КлассВредФакт CustomMembers)

        
        /// <summary>
        /// Наименование.
        /// </summary>
        // *** Start programmer edit section *** (КлассВредФакт.Наименование CustomAttributes)

        // *** End programmer edit section *** (КлассВредФакт.Наименование CustomAttributes)
        [StrLen(255)]
        public virtual string Наименование
        {
            get
            {
                // *** Start programmer edit section *** (КлассВредФакт.Наименование Get start)

                // *** End programmer edit section *** (КлассВредФакт.Наименование Get start)
                string result = this.fНаименование;
                // *** Start programmer edit section *** (КлассВредФакт.Наименование Get end)

                // *** End programmer edit section *** (КлассВредФакт.Наименование Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (КлассВредФакт.Наименование Set start)

                // *** End programmer edit section *** (КлассВредФакт.Наименование Set start)
                this.fНаименование = value;
                // *** Start programmer edit section *** (КлассВредФакт.Наименование Set end)

                // *** End programmer edit section *** (КлассВредФакт.Наименование Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "КлассВредФактE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КлассВредФактE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КлассВредФактE", typeof(IIS.UchetMedosmotrov4.КлассВредФакт));
                }
            }
            
            /// <summary>
            /// "КлассВредФактL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КлассВредФактL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КлассВредФактL", typeof(IIS.UchetMedosmotrov4.КлассВредФакт));
                }
            }
        }
    }
}
