//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.UchetMedosmotrov4
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Период.
    /// </summary>
    // *** Start programmer edit section *** (Период CustomAttributes)

    // *** End programmer edit section *** (Период CustomAttributes)
    public enum Период
    {
        
        // *** Start programmer edit section *** (Период.РазВГод CustomAttributes)

        // *** End programmer edit section *** (Период.РазВГод CustomAttributes)
        РазВГод,
        
        // *** Start programmer edit section *** (Период.РазВДваГода CustomAttributes)

        // *** End programmer edit section *** (Период.РазВДваГода CustomAttributes)
        РазВДваГода,
    }
}
