//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.UchetMedosmotrov4
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Приказ МЗР.
    /// </summary>
    // *** Start programmer edit section *** (ПриказМЗР CustomAttributes)

    // *** End programmer edit section *** (ПриказМЗР CustomAttributes)
    [AutoAltered()]
    [Caption("Приказ МЗР")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ПриказМЗРE", new string[] {
            "НомерПункта as \'Номер пункта\'"})]
    [View("ПриказМЗРL", new string[] {
            "НомерПункта as \'Номер пункта\'"})]
    public class ПриказМЗР : ICSSoft.STORMNET.DataObject
    {
        
        private string fНомерПункта;
        
        // *** Start programmer edit section *** (ПриказМЗР CustomMembers)

        // *** End programmer edit section *** (ПриказМЗР CustomMembers)

        
        /// <summary>
        /// НомерПункта.
        /// </summary>
        // *** Start programmer edit section *** (ПриказМЗР.НомерПункта CustomAttributes)

        // *** End programmer edit section *** (ПриказМЗР.НомерПункта CustomAttributes)
        [StrLen(255)]
        public virtual string НомерПункта
        {
            get
            {
                // *** Start programmer edit section *** (ПриказМЗР.НомерПункта Get start)

                // *** End programmer edit section *** (ПриказМЗР.НомерПункта Get start)
                string result = this.fНомерПункта;
                // *** Start programmer edit section *** (ПриказМЗР.НомерПункта Get end)

                // *** End programmer edit section *** (ПриказМЗР.НомерПункта Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПриказМЗР.НомерПункта Set start)

                // *** End programmer edit section *** (ПриказМЗР.НомерПункта Set start)
                this.fНомерПункта = value;
                // *** Start programmer edit section *** (ПриказМЗР.НомерПункта Set end)

                // *** End programmer edit section *** (ПриказМЗР.НомерПункта Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ПриказМЗРE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПриказМЗРE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПриказМЗРE", typeof(IIS.UchetMedosmotrov4.ПриказМЗР));
                }
            }
            
            /// <summary>
            /// "ПриказМЗРL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПриказМЗРL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПриказМЗРL", typeof(IIS.UchetMedosmotrov4.ПриказМЗР));
                }
            }
        }
    }
}
